# Generated by Django 4.0.6 on 2022-08-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='sharedUsers',
        ),
        migrations.AlterField(
            model_name='todos',
            name='dueDate',
            field=models.CharField(max_length=100),
        ),
    ]
