# Generated by Django 4.0.6 on 2022-08-24 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todos_sharedusers_alter_todos_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('dueDate', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
