# Generated by Django 4.0.6 on 2022-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_allfolders_delete_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='folder',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
